services:
  weather-entertainment-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: ${DATABASE_URL:-"mysql://user:password@localhost:3306/db"}
      RABBITMQ_URL: ${RABBITMQ_URL:-"amqp://guest:guest@localhost:5672/"}
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://weather-entertainment-backend:8006/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
